server:
  address: prod.webapp.com
  port: 7070
pricing-server:
  host: prod.pricing.com
  port: 7171
database:
  host: prod.database.com
  port: 7272
heartbeat:
  interval: 5
  message: Heartbeat from prod ${heartbeat.interval} ${spring.application.name}