server:
  address: uat.webapp.com
  port: 7070
pricing-server:
  host: uat.pricing.com
  port: 7171
database:
  host: uat.database.com
  port: 7272
heartbeat:
  interval: 5
  message: Heartbeat from uat ${heartbeat.interval} ${spring.application.name}