server:
  address: localhost
  port: 7070
pricing-server:
  host: dev.pricing.com
  port: 7171
database:
  host: dev.database.com
  port: 7272
heartbeat:
  interval: 5
  message: Heartbeat from dev ${heartbeat.interval} ${spring.application.name}